FROM ubuntu:latest

RUN apt-get update
RUN apt-get install -y python3 python3-pip git vim curl

COPY . /app
WORKDIR /app

RUN pip3 install -r requirements.txt

ENV ENV=prod
ENV DEBUG=true

EXPOSE 8000

CMD python3 app.py
